import http from 'node:http';
import crypto from 'node:crypto';

const PORT=Number(process.env.PORT||8787);
const MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const TOKEN=process.env.JARVIS_API_TOKEN||'';
const CORS=process.env.CORS_ORIGIN||'*';
const state={tasks:[],memory:[],approvals:[],audit:[]};
const agents=[['01','Triage / Router'],['02','Executive'],['03','Research'],['04','Email'],['05','Calendar'],['06','Finance'],['07','Contacts'],['08','Data / Logic'],['09','Memory'],['10','Voice'],['11','Policy']];
function id(){return crypto.randomUUID()}
function json(res,status,payload){res.writeHead(status,{'content-type':'application/json; charset=utf-8','access-control-allow-origin':CORS,'access-control-allow-headers':'content-type,authorization','access-control-allow-methods':'GET,POST,PATCH,OPTIONS'});res.end(JSON.stringify(payload))}
function auth(req){if(!TOKEN)return true;return req.headers.authorization===`Bearer ${TOKEN}`}
async function body(req){let b='';for await(const c of req){b+=c;if(b.length>2_000_000)throw Error('request too large')}return b?JSON.parse(b):{}}
async function openai(text){const key=process.env.OPENAI_API_KEY;if(!key)return {reply:'Rdzeń JARVIS działa, ale OPENAI_API_KEY nie jest skonfigurowany po stronie backendu.',model:null};const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:MODEL,input:[{role:'system',content:[{type:'input_text',text:'You are JARVIS 2.0, a precise personal AI executive assistant. Respond in Polish unless the user asks otherwise. Never claim an external action was completed unless a tool actually completed it.'}]},{role:'user',content:[{type:'input_text',text}]}]})});if(!r.ok)throw Error(`OpenAI ${r.status}`);const d=await r.json();return {reply:d.output_text||'Brak odpowiedzi.',model:MODEL,response_id:d.id}}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host}`);if(req.method==='OPTIONS')return json(res,204,{});if(!auth(req))return json(res,401,{error:'unauthorized'});try{if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,version:'3.0.0',service:'jarvis-backend'});if(req.method==='GET'&&u.pathname==='/api/agents')return json(res,200,{agents:agents.map(([id,name])=>({id,name,status:'online'}))});if(req.method==='GET'&&u.pathname==='/api/tasks')return json(res,200,{tasks:state.tasks});if(req.method==='POST'&&u.pathname==='/api/tasks'){const x=await body(req);const t={id:id(),title:String(x.title||'Untitled task'),status:'planned',priority:x.priority||'medium',created_at:new Date().toISOString()};state.tasks.push(t);return json(res,201,t)}if(req.method==='PATCH'&&u.pathname.startsWith('/api/tasks/')){const tid=u.pathname.split('/').pop();const t=state.tasks.find(x=>x.id===tid);if(!t)return json(res,404,{error:'not found'});Object.assign(t,await body(req));return json(res,200,t)}if(req.method==='GET'&&u.pathname==='/api/memory')return json(res,200,{memory:state.memory});if(req.method==='POST'&&u.pathname==='/api/memory'){const x=await body(req);const m={id:id(),text:String(x.text||''),created_at:new Date().toISOString()};state.memory.push(m);return json(res,201,m)}if(req.method==='GET'&&u.pathname==='/api/approvals')return json(res,200,{approvals:state.approvals});if(req.method==='POST'&&u.pathname==='/api/approvals'){const x=await body(req);const a={id:id(),action:String(x.action||''),status:'pending',created_at:new Date().toISOString()};state.approvals.push(a);return json(res,201,a)}if(req.method==='PATCH'&&u.pathname.startsWith('/api/approvals/')){const aid=u.pathname.split('/').pop();const a=state.approvals.find(x=>x.id===aid);if(!a)return json(res,404,{error:'not found'});Object.assign(a,await body(req));return json(res,200,a)}if(req.method==='GET'&&u.pathname==='/api/audit')return json(res,200,{audit:state.audit});if(req.method==='POST'&&u.pathname==='/api/chat'){const x=await body(req);const text=String(x.text||'').trim();if(!text)return json(res,400,{error:'text required'});const trace=id();const result=await openai(text);state.audit.push({trace_id:trace,type:'chat',text,created_at:new Date().toISOString()});return json(res,200,{trace_id:trace,...result})}return json(res,404,{error:'not found'})}catch(e){return json(res,500,{error:e?.message||'internal error'})}}
http.createServer(route).listen(PORT,()=>console.log(`JARVIS backend listening on :${PORT}`));
