package com.omega7.server;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpServer;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;
import java.io.InputStream;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.sql.*;
import java.util.Base64;
import java.util.UUID;
import java.util.concurrent.Executors;

/** Blind Ω7 relay. It never decrypts or logs message plaintext. Put it behind an HTTPS reverse proxy. */
public final class Main {
  private static final ObjectMapper JSON=new ObjectMapper(); private static final SecureRandom RANDOM=new SecureRandom();
  private static final int MAX_DEVICES=7, MAX_BODY=384*1024;
  private static final String DB_URL=env("OMEGA7_DB_URL","jdbc:postgresql://localhost:5432/omega7");
  private static final String DB_USER=env("OMEGA7_DB_USER","omega7"), DB_PASSWORD=env("OMEGA7_DB_PASSWORD","change-me");
  private static final byte[] AUTH_SECRET=env("OMEGA7_AUTH_SECRET","change-me-now").getBytes(StandardCharsets.UTF_8);
  private static final String BOOTSTRAP_SECRET=env("OMEGA7_BOOTSTRAP_SECRET","change-me-bootstrap");

  public static void main(String[] args)throws Exception{try(Connection c=db()){init(c);}int port=Integer.parseInt(env("PORT","8080"));HttpServer s=HttpServer.create(new InetSocketAddress("0.0.0.0",port),128);s.createContext("/v1/health",Main::health);s.createContext("/v1/bootstrap",Main::bootstrap);s.createContext("/v1/pair/invites",Main::createInvite);s.createContext("/v1/devices/register",Main::register);s.createContext("/v1/keys",Main::keys);s.createContext("/v1/messages",Main::messages);s.createContext("/v1/sync",Main::sync);s.setExecutor(Executors.newFixedThreadPool(Math.max(4,Runtime.getRuntime().availableProcessors())));s.start();System.out.println("Ω7 relay listening on "+port);}
  private static void init(Connection c)throws Exception{try(InputStream in=Main.class.getResourceAsStream("/schema.sql")){if(in==null)throw new IllegalStateException("schema.sql missing");for(String q:new String(in.readAllBytes(),StandardCharsets.UTF_8).split(";"))if(!q.isBlank())try(Statement s=c.createStatement()){s.execute(q);}}}
  private static void health(HttpExchange x)throws IOException{try(Connection c=db();Statement s=c.createStatement()){s.executeQuery("SELECT 1");json(x,200,obj().put("status","ok"));}catch(Exception e){json(x,503,obj().put("status","degraded"));}}
  private static void bootstrap(HttpExchange x)throws IOException{if(!method(x,"POST"))return;if(!BOOTSTRAP_SECRET.equals(x.getRequestHeaders().getFirst("X-Bootstrap-Secret"))){json(x,403,error("Brak uprawnień."));return;}JsonNode b=readJson(x);String g=text(b,"groupId",128);int d=integer(b,"deviceId",1,127);require(g!=null,"groupId");try(Connection c=db()){c.setAutoCommit(false);try(PreparedStatement p=c.prepareStatement("INSERT INTO omega_groups(group_id) VALUES(?) ON CONFLICT DO NOTHING")){p.setString(1,g);p.executeUpdate();}byte[] token=random(32);insertDevice(c,g,d,b,token);c.commit();json(x,201,obj().put("deviceId",d).put("authToken",tokenString(token)));java.util.Arrays.fill(token,(byte)0);}catch(Exception e){json(x,409,error("Nie można utworzyć właściciela grupy."));}}
  private static void createInvite(HttpExchange x)throws IOException{if(!method(x,"POST"))return;String auth=auth(x);if(auth==null){json(x,401,error("Brak uwierzytelnienia."));return;}JsonNode b=readJson(x);String g=text(b,"groupId",128);int owner=integer(b,"ownerDeviceId",1,127);require(g!=null,"groupId");try(Connection c=db()){if(!authorized(c,g,owner,auth)){json(x,403,error("Brak uprawnień."));return;}byte[] t=random(32);UUID id=UUID.randomUUID();try(PreparedStatement p=c.prepareStatement("INSERT INTO invites(invite_id,group_id,owner_device_id,token_hash,expires_at) VALUES(?,?,?,?,now()+interval '5 minutes')")){p.setObject(1,id);p.setString(2,g);p.setInt(3,owner);p.setBytes(4,hmac(t));p.executeUpdate();}json(x,201,obj().put("inviteId",id.toString()).put("expiresInSeconds",300).put("inviteToken",tokenString(t)));java.util.Arrays.fill(t,(byte)0);}catch(Exception e){json(x,503,error("Nie można utworzyć zaproszenia."));}}
  private static void register(HttpExchange x)throws IOException{if(!method(x,"POST"))return;JsonNode b=readJson(x);String g=text(b,"groupId",128),t=text(b,"inviteToken",512);int d=integer(b,"deviceId",1,127);require(g!=null&&t!=null,"groupId/inviteToken");try(Connection c=db()){c.setAutoCommit(false);if(consumeInvite(c,g,t)==null){c.rollback();json(x,403,error("Nieprawidłowe lub wygasłe zaproszenie."));return;}try(PreparedStatement l=c.prepareStatement("SELECT group_id FROM omega_groups WHERE group_id=? FOR UPDATE")){l.setString(1,g);try(ResultSet r=l.executeQuery()){if(!r.next()){c.rollback();json(x,404,error("Grupa nie istnieje."));return;}}}try(PreparedStatement q=c.prepareStatement("SELECT count(*) FROM devices WHERE group_id=? AND active=true")){q.setString(1,g);try(ResultSet r=q.executeQuery()){r.next();if(r.getInt(1)>=MAX_DEVICES){c.rollback();json(x,409,error("Limit 7 urządzeń został osiągnięty."));return;}}}byte[] token=random(32);insertDevice(c,g,d,b,token);c.commit();json(x,201,obj().put("deviceId",d).put("authToken",tokenString(token)));java.util.Arrays.fill(token,(byte)0);}catch(Exception e){json(x,400,error("Rejestracja urządzenia odrzucona."));}}
  private static void insertDevice(Connection c,String g,int d,JsonNode b,byte[] token)throws Exception{try(PreparedStatement p=c.prepareStatement("INSERT INTO devices(group_id,device_id,registration_id,identity_key,signed_prekey_id,signed_prekey,signed_prekey_signature,kyber_prekey_id,kyber_prekey,kyber_prekey_signature,auth_token_hash) VALUES (?,?,?,?,?,?,?,?,?,?,?)")){p.setString(1,g);p.setInt(2,d);p.setInt(3,integer(b,"registrationId",1,Integer.MAX_VALUE));p.setBytes(4,b64(b,"identityKey"));p.setInt(5,integer(b,"signedPreKeyId",1,Integer.MAX_VALUE));p.setBytes(6,b64(b,"signedPreKey"));p.setBytes(7,b64(b,"signedPreKeySignature"));p.setInt(8,integer(b,"kyberPreKeyId",1,Integer.MAX_VALUE));p.setBytes(9,b64(b,"kyberPreKey"));p.setBytes(10,b64(b,"kyberPreKeySignature"));p.setBytes(11,hmac(token));p.executeUpdate();}}
  private static UUID consumeInvite(Connection c,String g,String t)throws Exception{try(PreparedStatement p=c.prepareStatement("UPDATE invites SET consumed_at=now() WHERE group_id=? AND token_hash=? AND consumed_at IS NULL AND expires_at>now() RETURNING invite_id")){p.setString(1,g);p.setBytes(2,hmac(t.getBytes(StandardCharsets.UTF_8)));try(ResultSet r=p.executeQuery()){return r.next()?UUID.fromString(r.getString(1)):null;}}}
  private static void keys(HttpExchange x)throws IOException{if(!method(x,"GET"))return;String[] p=x.getRequestURI().getPath().split("/");if(p.length<5){json(x,400,error("Brak identyfikatora."));return;}String g=p[3];int d;try{d=Integer.parseInt(p[4]);}catch(Exception e){json(x,400,error("Nieprawidłowe urządzenie."));return;}try(Connection c=db();PreparedStatement q=c.prepareStatement("SELECT registration_id,identity_key,signed_prekey_id,signed_prekey,signed_prekey_signature,kyber_prekey_id,kyber_prekey,kyber_prekey_signature FROM devices WHERE group_id=? AND device_id=? AND active=true")){q.setString(1,g);q.setInt(2,d);try(ResultSet r=q.executeQuery()){if(!r.next()){json(x,404,error("Urządzenie nie istnieje."));return;}ObjectNode out=obj().put("deviceId",d).put("registrationId",r.getInt(1)).put("identityKey",b64(r.getBytes(2))).put("signedPreKeyId",r.getInt(3)).put("signedPreKey",b64(r.getBytes(4))).put("signedPreKeySignature",b64(r.getBytes(5))).put("kyberPreKeyId",r.getInt(6)).put("kyberPreKey",b64(r.getBytes(7))).put("kyberPreKeySignature",b64(r.getBytes(8)));json(x,200,out);}}catch(Exception e){json(x,503,error("Błąd usługi."));}}
  private static void messages(HttpExchange x)throws IOException{if(!method(x,"POST"))return;String a=auth(x);if(a==null){json(x,401,error("Brak uwierzytelnienia."));return;}JsonNode b=readJson(x);String g=text(b,"groupId",128),idem=text(b,"idempotencyKey",128);int sender=integer(b,"senderDeviceId",1,127),recipient=integer(b,"recipientDeviceId",1,127);byte[] ct=b64(b,"ciphertext");if(ct.length>256*1024){json(x,413,error("Koperta jest zbyt duża."));return;}try(Connection c=db()){if(!authorized(c,g,sender,a)){json(x,403,error("Brak uprawnień."));return;}try(PreparedStatement p=c.prepareStatement("INSERT INTO messages(group_id,recipient_device_id,sender_device_id,idempotency_key,ciphertext) VALUES(?,?,?,?,?) ON CONFLICT(group_id,recipient_device_id,idempotency_key) DO NOTHING")){p.setString(1,g);p.setInt(2,recipient);p.setInt(3,sender);p.setString(4,idem);p.setBytes(5,ct);p.executeUpdate();}json(x,202,obj().put("accepted",true));}catch(Exception e){json(x,503,error("Błąd zapisu."));}}
  private static void sync(HttpExchange x)throws IOException{if(!method(x,"GET"))return;String a=auth(x),g=q(x,"groupId"),curs=q(x,"cursor");int d;try{d=Integer.parseInt(q(x,"deviceId"));}catch(Exception e){json(x,400,error("Nieprawidłowe urządzenie."));return;}long cur=curs==null?0:Long.parseLong(curs);if(a==null){json(x,401,error("Brak uwierzytelnienia."));return;}try(Connection c=db()){if(!authorized(c,g,d,a)){json(x,403,error("Brak uprawnień."));return;}try(PreparedStatement p=c.prepareStatement("SELECT seq,sender_device_id,idempotency_key,ciphertext,created_at FROM messages WHERE group_id=? AND recipient_device_id=? AND seq>? ORDER BY seq ASC LIMIT 100")){p.setString(1,g);p.setInt(2,d);p.setLong(3,cur);try(ResultSet r=p.executeQuery()){ArrayNode out=JSON.createArrayNode();long next=cur;while(r.next()){next=r.getLong(1);out.add(obj().put("seq",next).put("senderDeviceId",r.getInt(2)).put("idempotencyKey",r.getString(3)).put("ciphertext",b64(r.getBytes(4))).put("createdAt",r.getTimestamp(5).toInstant().toString()));}json(x,200,obj().put("cursor",next).set("messages",out));}}}catch(Exception e){json(x,503,error("Błąd synchronizacji."));}}
  private static boolean authorized(Connection c,String g,int d,String token)throws Exception{try(PreparedStatement p=c.prepareStatement("SELECT 1 FROM devices WHERE group_id=? AND device_id=? AND active=true AND auth_token_hash=?")){p.setString(1,g);p.setInt(2,d);p.setBytes(3,hmac(Base64.getUrlDecoder().decode(token)));try(ResultSet r=p.executeQuery()){return r.next();}}}
  private static String auth(HttpExchange x){String h=x.getRequestHeaders().getFirst("Authorization");return h!=null&&h.startsWith("Bearer ")?h.substring(7):null;} private static Connection db()throws SQLException{return DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWORD);}
  private static byte[] hmac(byte[] d)throws Exception{Mac m=Mac.getInstance("HmacSHA256");m.init(new SecretKeySpec(AUTH_SECRET,"HmacSHA256"));return m.doFinal(d);} private static byte[] random(int n){byte[] b=new byte[n];RANDOM.nextBytes(b);return b;} private static String tokenString(byte[] b){return Base64.getUrlEncoder().withoutPadding().encodeToString(b);} private static String b64(byte[] b){return Base64.getEncoder().encodeToString(b);} private static byte[] b64(JsonNode n,String f){String v=n.path(f).asText(null);if(v==null)throw new IllegalArgumentException(f);return Base64.getDecoder().decode(v);}
  private static JsonNode readJson(HttpExchange x)throws IOException{byte[] b=x.getRequestBody().readNBytes(MAX_BODY+1);if(b.length>MAX_BODY)throw new IOException("body");return JSON.readTree(b);} private static String text(JsonNode n,String f,int m){String s=n.path(f).asText(null);return s!=null&&s.length()<=m?s:null;} private static int integer(JsonNode n,String f,int min,int max){int v=n.path(f).asInt(Integer.MIN_VALUE);if(v<min||v>max)throw new IllegalArgumentException(f);return v;} private static ObjectNode obj(){return JSON.createObjectNode();} private static ObjectNode error(String s){return obj().put("error",s);} private static boolean method(HttpExchange x,String m)throws IOException{if(!x.getRequestMethod().equals(m)){x.getResponseHeaders().set("Allow",m);json(x,405,error("Metoda niedozwolona."));return false;}return true;} private static String q(HttpExchange x,String k){String s=x.getRequestURI().getRawQuery();if(s==null)return null;for(String p:s.split("&")){String[] a=p.split("=",2);if(a.length==2&&a[0].equals(k))return a[1];}return null;} private static void json(HttpExchange x,int st,JsonNode n)throws IOException{byte[] b=JSON.writeValueAsBytes(n);x.getResponseHeaders().set("Content-Type","application/json; charset=utf-8");x.getResponseHeaders().set("Cache-Control","no-store");x.sendResponseHeaders(st,b.length);try(var o=x.getResponseBody()){o.write(b);}} private static String env(String k,String d){String v=System.getenv(k);return v==null||v.isBlank()?d:v;} private static void require(boolean ok,String s){if(!ok)throw new IllegalArgumentException(s);}
}
