import React from 'react';
import {Pressable,Text,View,StyleSheet,TextInput,ScrollView} from 'react-native';
export const C={bg:'#050812',panel:'#0b1020',panel2:'#10172a',line:'#1d2a45',text:'#eef4ff',muted:'#7f8ca8',cyan:'#45d7ff',green:'#54e39a',amber:'#ffc45a'};
export function Screen({children}:{children:React.ReactNode}){return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={s.screen}>{children}</ScrollView>}
export function Header({title,sub}:{title:string,sub?:string}){return <View style={s.header}><View><Text style={s.brand}>JARVIS <Text style={s.brandDim}>2.0</Text></Text><Text style={s.title}>{title}</Text>{sub&&<Text style={s.sub}>{sub}</Text>}</View><View style={s.live}><View style={s.dot}/><Text style={s.liveText}>LIVE</Text></View></View>}
export function Card({children,style}:{children:React.ReactNode,style?:any}){return <View style={[s.card,style]}>{children}</View>}
export function Stat({label,value,note}:{label:string,value:string,note:string}){return <Card style={{flex:1,minWidth:100}}><Text style={s.statLabel}>{label}</Text><Text style={s.stat}>{value}</Text><Text style={s.note}>{note}</Text></Card>}
export function Button({label,onPress,secondary=false}:{label:string,onPress:()=>void,secondary?:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[s.btn,secondary&&s.btn2,pressed&&{opacity:.72}]}><Text style={[s.btnText,secondary&&{color:C.cyan}]}>{label}</Text></Pressable>}
export function Field({value,onChange,placeholder}:{value:string,onChange:(v:string)=>void,placeholder:string}){return <TextInput value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={C.muted} style={s.field} autoCapitalize="none"/>}
export function Row({children}:{children:React.ReactNode}){return <View style={s.row}>{children}</View>}
export const s=StyleSheet.create({screen:{padding:18,paddingBottom:40,gap:14,backgroundColor:C.bg,minHeight:'100%'},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start',paddingTop:8},brand:{color:C.text,fontSize:15,fontWeight:'800',letterSpacing:3},brandDim:{color:C.cyan},title:{color:C.text,fontSize:29,fontWeight:'800',marginTop:8},sub:{color:C.muted,fontSize:12,marginTop:4},live:{flexDirection:'row',alignItems:'center',gap:6,borderWidth:1,borderColor:C.line,paddingHorizontal:10,paddingVertical:7,borderRadius:20},dot:{width:7,height:7,borderRadius:7,backgroundColor:C.green},liveText:{color:C.green,fontSize:10,fontWeight:'800',letterSpacing:1},card:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:18,padding:16,gap:9},statLabel:{color:C.muted,fontSize:9,fontWeight:'800',letterSpacing:1},stat:{color:C.text,fontSize:25,fontWeight:'800'},note:{color:C.muted,fontSize:10},row:{flexDirection:'row',gap:10,flexWrap:'wrap'},btn:{backgroundColor:C.cyan,borderRadius:13,paddingVertical:13,paddingHorizontal:16,alignItems:'center'},btn2:{backgroundColor:C.panel2,borderWidth:1,borderColor:C.line},btnText:{color:'#041018',fontWeight:'800',fontSize:12},field:{backgroundColor:C.panel2,borderColor:C.line,borderWidth:1,borderRadius:13,color:C.text,paddingHorizontal:14,paddingVertical:13,fontSize:14}})
