import React,{useEffect,useState} from 'react';
import {Text,View,StyleSheet,ActivityIndicator,Pressable} from 'react-native';
import * as Speech from 'expo-speech';
import {Screen,Header,Card,Stat,Button,Field,C,Row} from '@/components/ui';
import {chat,getAgents,getTasks,getApprovals} from '@/lib/api';
import {VoiceButton} from '@/components/VoiceButton';
import {registerPush} from '@/lib/notifications';
export default function Home(){const[q,setQ]=useState('');const[busy,setBusy]=useState(false);const[reply,setReply]=useState('Witaj. JARVIS 2.0 jest gotowy. Czekam na polecenie.');const[stats,setStats]=useState({agents:11,tasks:37,approvals:0});useEffect(()=>{registerPush().catch(()=>null);(async()=>{try{const[a,t,p]=await Promise.all([getAgents(),getTasks(),getApprovals()]);setStats({agents:a.agents?.length??11,tasks:t.tasks?.length??0,approvals:(p.approvals||[]).filter((x:any)=>x.status==='pending').length})}catch{}})()},[]);const send=async(text=q)=>{if(!text.trim())return;setBusy(true);try{const r=await chat(text);const out=r.reply||'Polecenie przyjęte.';setReply(out);Speech.speak(out,{language:'pl-PL',rate:.98});}catch{setReply('Brak połączenia z rdzeniem JARVIS. Sprawdź adres API w Ustawieniach.')}finally{setBusy(false);setQ('')}};return <Screen><Header title="Command Center" sub="ANDROID EXECUTIVE AI · ONLINE"/><Card style={sx.hero}><Text style={sx.kicker}>NEURAL COMMAND LAYER</Text><Text style={sx.heroTitle}>Think. Route. Act.</Text><Text style={sx.heroText}>Głos, tekst, pamięć, zadania, zgody i automatyzacje w jednym centrum dowodzenia.</Text><Row><Button label="Morning Brief" onPress={()=>send('Przygotuj mi dzisiejszy briefing')}/><Button label="Priorytety" secondary onPress={()=>send('Przeanalizuj moje zadania i ustal priorytety')}/></Row></Card><Row><Stat label="AGENTS" value={String(stats.agents)} note="online / standby"/><Stat label="APPROVALS" value={String(stats.approvals)} note="pending"/></Row><Row><Stat label="TASKS" value={String(stats.tasks)} note="loaded"/><Stat label="VOICE" value="READY" note="STT + TTS"/></Row><Card><Text style={sx.section}>JARVIS CONSOLE</Text><View style={sx.reply}><Text style={sx.jarvis}>JARVIS</Text><Text style={sx.replyText} selectable>{reply}</Text></View><Field value={q} onChange={setQ} placeholder="Powiedz lub wpisz polecenie…"/><Row><VoiceButton onText={(text)=>{setQ(text);send(text)}}/>{busy?<ActivityIndicator color={C.cyan}/>:<Button label="EXECUTE ↗" onPress={()=>send()}/>}<Pressable onPress={()=>Speech.speak(reply,{language:'pl-PL'})}><Text style={sx.speak}>▶ ODTWÓRZ</Text></Pressable></Row></Card><Card><Text style={sx.section}>LIVE ACTIVITY</Text>{['Native voice pipeline armed','Backend context loaded','Approval policy armed','Push notification registration ready'].map((x,i)=><View key={i} style={sx.activity}><View style={sx.aDot}/><Text style={sx.activityText}>{x}</Text><Text style={sx.min}>{i+1}m</Text></View>)}</Card></Screen>}
const sx=StyleSheet.create({hero:{padding:20},kicker:{color:C.cyan,fontSize:9,fontWeight:'800',letterSpacing:2},heroTitle:{color:C.text,fontSize:30,fontWeight:'900',marginTop:6},heroText:{color:C.muted,lineHeight:20},section:{color:C.text,fontSize:11,fontWeight:'900',letterSpacing:1},reply:{backgroundColor:'#070c18',borderRadius:13,padding:14,borderWidth:1,borderColor:C.line},jarvis:{color:C.cyan,fontSize:9,fontWeight:'900',letterSpacing:1},replyText:{color:C.text,lineHeight:20,marginTop:6},activity:{flexDirection:'row',alignItems:'center',gap:9,paddingVertical:6},aDot:{width:6,height:6,borderRadius:6,backgroundColor:C.green},activityText:{color:C.text,fontSize:12,flex:1},min:{color:C.muted,fontSize:10},speak:{color:C.cyan,fontWeight:'800',fontSize:11,padding:13}});
